In [64]:
import numpy as np
import pandas as pd
import luxpy as lp
np.set_printoptions(suppress=False) 

In [65]:
ies = lp.toolboxes.iolidfiles.read_lamp_data('ies/10.ies')

In [66]:
n_h_angles = len(ies['h_angs'])
n_v_angles = len(ies['v_angs'])

# create numpy array and insert intensity values(multiplied by candela_mult)
cd = np.zeros((n_h_angles, n_v_angles))

for i in range(n_h_angles):
    end_angles = n_v_angles*(i+1)
    cd[i] = ies['candela_values'][i*n_v_angles:end_angles]*ies['candela_mult']

In [68]:
ies['h_angs']

array([-90. , -85. , -75. , -65. , -55. , -47.5, -42.5, -37.5, -33. ,
       -29. , -25.5, -22.5, -19.5, -17. , -15. , -13. , -11. ,  -9. ,
        -7. ,  -5. ,  -3. ,  -1. ,   0. ,   1. ,   3. ,   5. ,   7. ,
         9. ,  11. ,  13. ,  15. ,  17. ,  19.5,  22.5,  25.5,  29. ,
        33. ,  37.5,  42.5,  47.5,  55. ,  65. ,  75. ,  85. ,  90. ])

In [69]:
ies['v_angs']

array([-90. , -85. , -75. , -65. , -55. , -47.5, -42.5, -37.5, -33. ,
       -29. , -25.5, -22.5, -19.5, -17. , -15. , -13. , -11. ,  -9. ,
        -7. ,  -5. ,  -3. ,  -1. ,   0. ,   1. ,   3. ,   5. ,   7. ,
         9. ,  11. ,  13. ,  15. ,  17. ,  19.5,  22.5,  25.5,  29. ,
        33. ,  37.5,  42.5,  47.5,  55. ,  65. ,  75. ,  85. ,  90. ])

In [71]:
cd

array([[ 1.79,  1.79,  1.79, ...,  1.79,  1.79,  1.79],
       [ 2.03,  2.35,  3.14, ...,  2.15,  1.82,  1.73],
       [ 2.52,  4.76, 34.4 , ...,  6.04,  1.7 ,  1.6 ],
       ...,
       [ 2.1 ,  2.52, 10.61, ...,  1.09,  0.8 ,  0.72],
       [ 1.26,  1.28,  1.5 , ...,  0.95,  0.83,  0.8 ],
       [ 0.84,  0.84,  0.84, ...,  0.84,  0.84,  0.84]])

In [72]:
cd.shape

(45, 45)

In [73]:
v_diff = np.diff(ies['v_angs'])
v_diff

array([ 5. , 10. , 10. , 10. ,  7.5,  5. ,  5. ,  4.5,  4. ,  3.5,  3. ,
        3. ,  2.5,  2. ,  2. ,  2. ,  2. ,  2. ,  2. ,  2. ,  2. ,  1. ,
        1. ,  2. ,  2. ,  2. ,  2. ,  2. ,  2. ,  2. ,  2. ,  2.5,  3. ,
        3. ,  3.5,  4. ,  4.5,  5. ,  5. ,  7.5, 10. , 10. , 10. ,  5. ])

In [74]:
zonal_constant = np.zeros((len(ies['h_angs'])-1,len(v_diff)))

for i, (a, b) in enumerate(zip(ies['h_angs'][:-1], ies['h_angs'][1:])):
    zonal_constant[i] = [diff*np.pi/180*(np.sin(b*np.pi/180) - np.sin(a*np.pi/180)) for diff in v_diff]

In [75]:
zonal_constant.shape

(44, 44)

average candela for each foursome of angles 

In [80]:
average_cd = np.zeros((cd.shape[0]-1, cd.shape[1]-1))

for i in range(cd.shape[0]-1):
    average_cd[i] = [(cd[i][j] + cd[i][j+1] + cd[i+1][j] + cd[i+1][j+1])/4 for j in range(cd.shape[1]-1)]

In [81]:
np.set_printoptions(suppress=False) 
average_cd

array([[  1.99  ,   2.2675,   2.7975, ...,   2.15  ,   1.8875,   1.7825],
       [  2.915 ,  11.1625,  34.61  , ...,  17.255 ,   2.9275,   1.7125],
       [  5.1725,  31.1275, 138.4475, ...,  85.465 ,   7.64  ,   1.7425],
       ...,
       [  3.0925,  14.4   ,  90.52  , ...,  46.0225,   2.885 ,   0.8225],
       [  1.79  ,   3.9775,  15.8375, ...,   7.035 ,   0.9175,   0.7875],
       [  1.055 ,   1.115 ,   1.295 , ...,   0.9425,   0.865 ,   0.8275]])

In [82]:
average_cd.shape

(44, 44)

In [83]:
lumen_array = average_cd * zonal_constant

In [84]:
lumen_array.sum()

29972.57730570301